---
openapi: 3.1.0
info:
  title: FountainAI LLM Gateway
  description: Proxy to any LLM with function-calling support.
  version: 2.0.0
servers:
  - url: http://llm-gateway.fountain.coach/api/v1
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics_metrics_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
  /chat:
    post:
      tags:
        - Chat
      summary: Chat with Planner Objective
      description: >
        Receives the user's objective, loads available tools,
        and delegates reasoning to GPT.
      operationId: chatWithObjective
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cot:
                    title: Chain of Thought
                    description: Reasoning steps produced by the model
                    type: array
                    items:
                      type: string
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /chat/{id}/cot:
    get:
      summary: Fetch stored Chain-of-Thought
      operationId: getChatCoT
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retrieved reasoning
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  cot:
                    type: string
                  cot_summary:
                    type: string
        "404":
          description: Not Found
      security:
        - bearerAuth: []
  /sentinel/consult:
    post:
      tags:
        - Sentinel
      summary: Consult Security Sentinel
      description: >
        Sends a summary of a risky operation to the security_sentinel role.
      operationId: sentinelConsult
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecurityCheckRequest'
      responses:
        "200":
          description: Decision
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDecision'
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ChatRequest:
      title: ChatRequest
      type: object
      required:
        - model
        - messages
      properties:
        model:
          type: string
          title: Model
        messages:
          title: Messages
          type: array
          items:
            $ref: '#/components/schemas/MessageObject'
        functions:
          title: Functions
          type: array
          items:
            $ref: '#/components/schemas/FunctionObject'
        function_call:
          title: Function Call
          oneOf:
            - type: string
              enum: [auto]
            - $ref: '#/components/schemas/FunctionCallObject'
        include_cot:
          title: Include Chain of Thought
          description: When true, reasoning steps are returned and logged
          type: boolean
    SecurityCheckRequest:
      title: SecurityCheckRequest
      type: object
      required:
        - summary
        - user
        - resources
      properties:
        summary:
          type: string
        user:
          type: string
        resources:
          type: array
          items:
            type: string
    SecurityDecision:
      title: SecurityDecision
      type: object
      required:
        - decision
      properties:
        decision:
          type: string
          enum: [allow, deny, escalate]
    FunctionCallObject:
      title: FunctionCallObject
      type: object
      properties:
        name:
          type: string
      required:
        - name
    MessageObject:
      title: MessageObject
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          description: Role of the sender (e.g. user, assistant)
        content:
          type: string
          description: Message text content
    FunctionObject:
      title: FunctionObject
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the function
        description:
          type: string
          description: Optional description of the function
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string

© 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.
