# SwiftLint configuration for FountainCoach project

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - identifier_name

line_length: 120

# © 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.
