version: '3.9'
services:
  typesense:
    image: typesense/typesense:0.25.0
    environment:
      - TYPESENSE_API_KEY=xyz
    ports:
      - "8108:8108"
  tools-factory:
    build: ../../Generated/Server/tools-factory
    environment:
      - TYPESENSE_URL=http://typesense:8108
      - TYPESENSE_API_KEY=xyz
    ports:
      - "8087:8080"
    depends_on:
      - typesense
  function-caller:
    build: ../../Generated/Server/function-caller
    environment:
      - TYPESENSE_URL=http://typesense:8108
      - TYPESENSE_API_KEY=xyz
      - FUNCTIONS_CACHE_PATH=functions-cache.json
    ports:
      - "8088:8080"
    depends_on:
      - typesense
