//
// AnalyticsRuleParametersSourceEventsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRuleParametersSourceEventsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var type: String
    public var weight: Float
    public var name: String

    public init(type: String, weight: Float, name: String) {
        self.type = type
        self.weight = weight
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case weight
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(weight, forKey: .weight)
        try container.encode(name, forKey: .name)
    }
}

