//
// AnalyticsRuleUpsertSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRuleUpsertSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case popularQueries = "popular_queries"
        case nohitsQueries = "nohits_queries"
        case counter = "counter"
    }
    public var type: ModelType
    public var params: AnalyticsRuleParameters

    public init(type: ModelType, params: AnalyticsRuleParameters) {
        self.type = type
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(params, forKey: .params)
    }
}

