//
// AnalyticsRuleParametersDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRuleParametersDestination: Sendable, Codable, ParameterConvertible, Hashable {

    public var collection: String
    public var counterField: String?

    public init(collection: String, counterField: String? = nil) {
        self.collection = collection
        self.counterField = counterField
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collection
        case counterField = "counter_field"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collection, forKey: .collection)
        try container.encodeIfPresent(counterField, forKey: .counterField)
    }
}

