//
// AnalyticsRuleParametersSource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRuleParametersSource: Sendable, Codable, ParameterConvertible, Hashable {

    public var collections: [String]
    public var events: [AnalyticsRuleParametersSourceEventsInner]?

    public init(collections: [String], events: [AnalyticsRuleParametersSourceEventsInner]? = nil) {
        self.collections = collections
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collections
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collections, forKey: .collections)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

