//
// AnalyticsRulesRetrieveSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRulesRetrieveSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var rules: [AnalyticsRuleSchema]?

    public init(rules: [AnalyticsRuleSchema]? = nil) {
        self.rules = rules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rules, forKey: .rules)
    }
}

