//
// AnalyticsRuleParameters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsRuleParameters: Sendable, Codable, ParameterConvertible, Hashable {

    public var source: AnalyticsRuleParametersSource
    public var destination: AnalyticsRuleParametersDestination
    public var limit: Int?
    public var expandQuery: Bool?

    public init(source: AnalyticsRuleParametersSource, destination: AnalyticsRuleParametersDestination, limit: Int? = nil, expandQuery: Bool? = nil) {
        self.source = source
        self.destination = destination
        self.limit = limit
        self.expandQuery = expandQuery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case destination
        case limit
        case expandQuery = "expand_query"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(destination, forKey: .destination)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(expandQuery, forKey: .expandQuery)
    }
}

