//
// AnalyticsEventCreateSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AnalyticsEventCreateSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var type: String
    public var name: String
    public var data: JSONValue

    public init(type: String, name: String, data: JSONValue) {
        self.type = type
        self.name = name
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encode(data, forKey: .data)
    }
}

