//
// ApiKeyDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiKeyDeleteResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** The id of the API key that was deleted */
    public var id: Int64

    public init(id: Int64) {
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ApiKeyDeleteResponse: Identifiable {}
