//
// CollectionUpdateSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CollectionUpdateSchema: Sendable, Codable, ParameterConvertible, Hashable {

    /** A list of fields for querying, filtering and faceting */
    public var fields: [Field]

    public init(fields: [Field]) {
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fields, forKey: .fields)
    }
}

