//
// CollectionAliasesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CollectionAliasesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var aliases: [CollectionAlias]

    public init(aliases: [CollectionAlias]) {
        self.aliases = aliases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aliases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aliases, forKey: .aliases)
    }
}

