//
// Debug200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Debug200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var version: String?

    public init(version: String? = nil) {
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

