//
// DeleteDocuments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteDocuments200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var numDeleted: Int

    public init(numDeleted: Int) {
        self.numDeleted = numDeleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numDeleted = "num_deleted"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numDeleted, forKey: .numDeleted)
    }
}

