//
// IndexAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum IndexAction: String, Sendable, Codable, CaseIterable {
    case create = "create"
    case update = "update"
    case upsert = "upsert"
    case emplace = "emplace"
}
