//
// ListStemmingDictionaries200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListStemmingDictionaries200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var dictionaries: [String]?

    public init(dictionaries: [String]? = nil) {
        self.dictionaries = dictionaries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dictionaries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dictionaries, forKey: .dictionaries)
    }
}

