//
// MultiSearchSearchesParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MultiSearchSearchesParameter: Sendable, Codable, ParameterConvertible, Hashable {

    /** When true, merges the search results from each search query into a single ordered set of hits. */
    public var union: Bool?
    public var searches: [MultiSearchCollectionParameters]

    public init(union: Bool? = nil, searches: [MultiSearchCollectionParameters]) {
        self.union = union
        self.searches = searches
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case union
        case searches
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(union, forKey: .union)
        try container.encode(searches, forKey: .searches)
    }
}

