//
// PresetsRetrieveSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PresetsRetrieveSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var presets: [PresetSchema]

    public init(presets: [PresetSchema]) {
        self.presets = presets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case presets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(presets, forKey: .presets)
    }
}

