//
// SearchResultRequestParamsVoiceQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchResultRequestParamsVoiceQuery: Sendable, Codable, ParameterConvertible, Hashable {

    public var transcribedQuery: String?

    public init(transcribedQuery: String? = nil) {
        self.transcribedQuery = transcribedQuery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transcribedQuery = "transcribed_query"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transcribedQuery, forKey: .transcribedQuery)
    }
}

