//
// SearchOverrideInclude.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchOverrideInclude: Sendable, Codable, ParameterConvertible, Hashable {

    /** document id that should be included */
    public var id: String
    /** position number where document should be included in the search results */
    public var position: Int

    public init(id: String, position: Int) {
        self.id = id
        self.position = position
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case position
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(position, forKey: .position)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SearchOverrideInclude: Identifiable {}
