//
// SearchOverrideRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchOverrideRule: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Match: String, Sendable, Codable, CaseIterable {
        case exact = "exact"
        case contains = "contains"
    }
    /** List of tag values to associate with this override rule. */
    public var tags: [String]?
    /** Indicates what search queries should be overridden */
    public var query: String?
    /** Indicates whether the match on the query term should be `exact` or `contains`. If we want to match all queries that contained the word `apple`, we will use the `contains` match instead.  */
    public var match: Match?
    /** Indicates that the override should apply when the filter_by parameter in a search query exactly matches the string specified here (including backticks, spaces, brackets, etc).  */
    public var filterBy: String?

    public init(tags: [String]? = nil, query: String? = nil, match: Match? = nil, filterBy: String? = nil) {
        self.tags = tags
        self.query = query
        self.match = match
        self.filterBy = filterBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
        case query
        case match
        case filterBy = "filter_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(query, forKey: .query)
        try container.encodeIfPresent(match, forKey: .match)
        try container.encodeIfPresent(filterBy, forKey: .filterBy)
    }
}

