//
// SearchOverridesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SearchOverridesResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var overrides: [SearchOverride]

    public init(overrides: [SearchOverride]) {
        self.overrides = overrides
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overrides
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(overrides, forKey: .overrides)
    }
}

