//
// StemmingDictionary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StemmingDictionary: Sendable, Codable, ParameterConvertible, Hashable {

    /** Unique identifier for the dictionary */
    public var id: String
    /** List of word mappings in the dictionary */
    public var words: [StemmingDictionaryWordsInner]

    public init(id: String, words: [StemmingDictionaryWordsInner]) {
        self.id = id
        self.words = words
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case words
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(words, forKey: .words)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension StemmingDictionary: Identifiable {}
