//
// StopwordsSetsRetrieveAllSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StopwordsSetsRetrieveAllSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var stopwords: [StopwordsSetSchema]

    public init(stopwords: [StopwordsSetSchema]) {
        self.stopwords = stopwords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stopwords
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(stopwords, forKey: .stopwords)
    }
}

