//
// UpdateDocuments200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDocuments200Response: Sendable, Codable, ParameterConvertible, Hashable {

    /** The number of documents that have been updated */
    public var numUpdated: Int

    public init(numUpdated: Int) {
        self.numUpdated = numUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numUpdated = "num_updated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numUpdated, forKey: .numUpdated)
    }
}

