---
openapi: 3.1.0
info:
  title: Security Sentinel Gateway Plugin
  description: >
    Consults the Security Sentinel role for allow/deny/escalate decisions.
  version: 1.0.0
servers:
  - url: http://security-sentinel.fountain.coach/api/v1
paths:
  /sentinel/consult:
    post:
      tags:
        - Sentinel
      summary: Consult Security Sentinel
      description: Sends a summary of a potentially destructive operation for a decision.
      operationId: sentinelConsult
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecurityCheckRequest'
      responses:
        '200':
          description: Decision
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDecision'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    SecurityCheckRequest:
      title: SecurityCheckRequest
      type: object
      required:
        - summary
        - user
        - resources
      properties:
        summary:
          type: string
        user:
          type: string
        resources:
          type: array
          items:
            type: string
    SecurityDecision:
      title: SecurityDecision
      type: object
      required:
        - decision
      properties:
        decision:
          type: string
          enum:
            - allow
            - deny
            - escalate
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type

© 2025 Contexter alias Benedikt Eickhoff 🛡️ All rights reserved.
